version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5440:5432"  # Exposing PostgreSQL on port 5440
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ../backend  # Ensure this path is correct
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/mydb
      CLERK_SECRET_KEY: sk_test_Z0n7KabEw4xNQGadmIjqXUxTIvYlGCjSoksOM9apAL
    depends_on:
      - db
    ports:
      - "3010:3010"

volumes:
  postgres_data:
